pipeline {
    agent any
    def pomfilepath=sample-maven-project/maven-archetype-quickstart/pom.xml
    stages {
    stage('maven install ') {
      steps {
        withMaven {
          sh 'mvn clean install'
        }
      }
    }

  }
}
