pipeline {
    agent any
    def pomfilepath=/var/lib/jenkins/workspace/test-maven-pipeline/pom.xml
    stages {
    stage('maven install') {
      steps {
        withMaven {
          sh 'mvn clean install'
        }
      }
    }

  }
}
