pipeline {
    agent any
    stages {
    stage('maven install') {
      steps {
        withMaven {
          sh 'mvn -f maven-archetype-quickstart/pom.xml clean install'
        }
      }
    }

  }
}
